services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_var:/var/www/html/var
      - app_public:/var/www/html/public_volume
    networks:
      - locmns_net
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - app_public:/var/www/html/public:ro
    networks:
      - locmns_net
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locmns
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - locmns_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - locmns_net
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  app_var:
  app_public:

networks:
  locmns_net:
    driver: bridge
